# wrangler.toml
name = 'chinadeveloper'
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[env.production]
name = "chinadeveloper"
routes = [
  { pattern = "chinadeveloper.net", zone_name = "chinadeveloper.net" },
  { pattern = "www.chinadeveloper.net", zone_name = "chinadeveloper.net" }
]

